### PR TITLE
feat(logging): Add porcelain CLI flag

### PR DESCRIPTION
**Pull request by JRasmusBm**
**Why** is the change needed?

Inspired by `git status --porcelain`, this flag allows users to specify that they want the output in a terse, parse-able format. Allows for doing something like the following.

```sh
creosote --porcelain | xargs poetry remove
```

**How** is the need addressed?

- Add an optional flag `--porcelain`.
    - When that flag is on:
        - Set logging LEVEL to `critical`, effectively disabling all logs.
        - Use a print statement to output a terse output for easy parsing.

What **side-effects** could the change have?

- This was done rather hastily. Maybe I should have refactored the
  solution. :innocent:

### CODE REVIEW

**Comment by JRasmusBm** [comment]
```
creosote$$$ › creosote                                                                                            
2022-02-07 09:36:19.888 | INFO     | creosote.parsers:get_modules_from_code:82 - Parsing src/creosote/checks.py
2022-02-07 09:36:19.888 | INFO     | creosote.parsers:get_modules_from_code:82 - Parsing src/creosote/__init__.py
2022-02-07 09:36:19.888 | INFO     | creosote.parsers:get_modules_from_code:82 - Parsing src/creosote/parsers.py
2022-02-07 09:36:19.889 | INFO     | creosote.parsers:get_modules_from_code:82 - Parsing src/creosote/models.py
2022-02-07 09:36:19.890 | INFO     | creosote.parsers:get_modules_from_code:82 - Parsing src/creosote/cli.py
2022-02-07 09:36:19.890 | INFO     | creosote.parsers:get_modules_from_code:82 - Parsing src/creosote/resolvers.py
2022-02-07 09:36:19.892 | INFO     | __main__:main:78 - Parsing pyproject.toml for packages
2022-02-07 09:36:19.892 | INFO     | __main__:main:82 - Resolving...
2022-02-07 09:36:20.147 | ERROR    | __main__:main:98 - Unused packages found: numpy, pandas
creosote!$$$ › creosote --porcelain                                                                               
numpy
pandas
```

**Comment by JRasmusBm** [comment]
And I'm completely open to flag name changes. I know the `porcelain` flag refers to the idea that it shouldn't ever change cause it will break things. If we want to change it later we might want to choose a different name :thinking:

**Comment by fredrikaverpil** [comment]
Sounds great, also super easy to implement. Great suggestion, thanks! 👍

**Review by fredrikaverpil — APPROVED** [review]

**Comment by JRasmusBm** [comment]
Sounds good to me! :smile: You'll have to do it though since the merge privileges are yours :innocent:

**Comment by fredrikaverpil** [comment]
I didn't merge it in straight away as-is, because I'm thinking maybe a better argument is `--format`. Then json, list (and others) etc can be provided, making this extensible. I'll make some adjustments, if you don't mind.

**Comment by JRasmusBm** [comment]
> I didn't merge it in straight away as-is, because I'm thinking maybe a better argument is `--format`. Then json, list (and others) etc can be provided, making this extensible. There's actually a whole lot more data one could potentially be interested in, if you would use this as an API and not a CLI, which would make sense to combine with `--format json`.
> 
> I'll make some minor adjustments, if you don't mind. Still greatly appreciate the time you took to whip this PR up! 🍡 

Sounds good! 😃

**Pull request merged**
