### PR TITLE
support PEP-582

### PR DESCRIPTION
**Pull request by lesleslie**
## Why is the change needed?

This add support for PEP-582 through PDM (__pypackages__). Currently, Creosote only supports dependencies in 
the 'site-packages' directory of a venv.

## What was done in this PR?

PDM-582 support and updated docs

## Are there any concerns, side-effects, additional notes?

I currently don't have tests for this (and maybe someone could help with that) but I've given it a good run through
in every situation I think someone would encounter - and it seems to work great!

## Checklist, when applicable

- [ ] Added test(s)
- [ x] Updated README.md
- [ ] Is this a backwards-compatibility breaking change?
- [ ] Resolves: #issue-number-here

### CODE REVIEW

**Comment by fredrikaverpil** [comment]
Hi @lesleslie and thanks for this.

I'm not super keen on having to maintain PEP-582 support since it was rejected. However, I thought this was already kind of supported, apart from the function which looks for the "site-packages" folder (not present int the `__pypackages__` dir) which you highlighted here.

Can you please try this version of Creosote, and see if it fits your needs?

```bash
# install creosote from pep-582 branch
$ pipx install --suffix=@pep-582 --force git+https://github.com/fredrikaverpil/creosote.git@main

# run creosote from pep-582 branch and point it to look at the __pypackages__ venv
$ creosote@pep-582 --venv __pypackages__

# uninstall
$ pipx uninstall creosote@pep-582
```

**Comment by lesleslie** [comment]
I’ll try that out and let you know.

And yes, apart from the function which looks for the "site-packages” folder , Creosote did work by setting
—venv to __pypackages__

**Comment by lesleslie** [comment]
The commands above did not work for me:

`
$ creosote@pep-582 --venv __pypackages__
Found dependencies in pyproject.toml: aioconsole, aiopath, click, inflection, pdm-bump, pydantic, tomli-w
Oh no, bloated venv! 🤢 🪣
Unused dependencies found: aioconsole, aiopath, click, inflection, pdm-bump, pydantic, tomli-w
`

I've got no problem maintaining my own fork with PEP-582 support. I thought people may find it helpful, but then again, as far as I know I'm the only one actually using it.

**Comment by fredrikaverpil** [comment]
Would be great to better understand why this is not working for you. Since you got this working in your fork, what exactly is missing?

To me, it looks like you did not point Creosote towards your Python source code using the `--paths` argument, like e.g.

```bash
creosote --venv __pypackages__ --paths src
```

It would be helpful if you could add the `--verbose` argument to your command and post the output here, so that it'll be easier for me to understand what's happening on your end.

**Comment by lesleslie** [comment]
Ok, that worked. I didn't have to set --paths in my version because of:
`
[tool.pdm.options]
config = [
    "python.use_venv",
    "true",
]
`
so I got in the habit of not using it. I did however have it set in .pre-commit-config.yaml:
`
args: [--paths, "myproject"]
`

**Comment by fredrikaverpil** [comment]
Ok, cool. Creosote defaults to `--paths src` so anyone who does not keep their python source code files in an "src" folder will have to specify a different location.

If this is what you need, I'm happy to merge the work done in #171

**Comment by lesleslie** [comment]
Yes, that does the trick.

Thank you!

**Comment by fredrikaverpil** [comment]
@lesleslie awesome 🎉 I'll get this released sometime today.

**Pull request closed without merging**
