### PR TITLE
Document PDM support

### PR DESCRIPTION
**Pull request by sanmai-NL**
## Why is the change needed?

Creosote supports PDM now, but this isn't documented.

## What was done in this PR?

Documented PDM support.

## Are there any concerns, side-effects, additional notes?

No.

## Checklist, when applicable

- ~[ ] Added test(s)~
- [x] Updated README.md
- ~[ ] Is this a backwards-compatibility breaking change?~
- ~[ ] Resolves: #issue-number-here~

### CODE REVIEW

**Comment by sanmai-NL** [comment]
Someplace else you commented that your wanted to keep PEP-621 support as the first row of the table. That would break alphabetical sorting though. Moreover, the PEP-621 support still stands out at first glance, since it is still quite at the top and the table and whole README is pretty brief. And to be honest, I expect your target audience to be more familiar with their favorite tools than with Python standards.

**Comment by sanmai-NL** [comment]
@fredrikaverpil 
The test failures are related to your source code. Can you make Ruff only run on changed files?

**Comment by fredrikaverpil** [comment]
I'm sorry about the failure as it is, like you say, unrelated to your PR. The problem has been fixed in #158 but there is an underlying problem I'll think about where I haven't pinned any of the static type checkers and I haven't limited the set of rules to check for.

> you commented that your wanted to keep PEP-621 support as the first row of the table. That would break alphabetical sorting though.

There's another PEP in that list so this alphabetical order is already broken. I might revise this order later.
By the way, did you know PEP-582 was [rejected](https://discuss.python.org/t/pep-582-python-local-packages-directory/963/430)?

Thanks for your contribution! 🎉

**Comment by sanmai-NL** [comment]
> By the way, did you know PEP-582 was [rejected](https://discuss.python.org/t/pep-582-python-local-packages-directory/963/430)?

Yes, but in case you think so, PDM doesn't depend on that. 🙂

**Comment by fredrikaverpil** [comment]
Yeah, it's optional with pdm, right?

I haven't used pdm really. Just tried it out some time ago.

**Pull request merged**
